# Confirmation drop message (MiniMessage Support!)
# https://webui.advntr.dev/
confirm-message: '<b><gold>(<yellow>i</yellow>)</gold></b> <gradient:#6BF965:#64F9F5>Tap <b><yellow>Q</yellow></b> Again to drop!</gradient>'

# Delay(in ticks, 20 ticks = 1 second) after drop item to reset drop confirmation notify
delay: 20 # 1secs

# Whitelist item add confirm to drop
# https://jd.papermc.io/paper/1.21.10/org/bukkit/Material.html
whitelist:
  - DIAMOND_SWORD
  - DIAMOND_PICKAXE
  - DIAMOND_AXE
  - DIAMOND_SHOVEL
  - DIAMOND_HOE
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - NETHERITE_SWORD
  - NETHERITE_PICKAXE
  - NETHERITE_AXE
  - NETHERITE_SHOVEL
  - NETHERITE_HOE
  - NETHERITE_HELMET
  - NETHERITE_CHESTPLATE
  - NETHERITE_LEGGINGS
  - NETHERITE_BOOTS
